"""Sphinx configuration file for nepse-client documentation."""

import os
import sys
from datetime import datetime


# Add project root to Python path
sys.path.insert(0, os.path.abspath(".."))

# Import project for version info
try:
    from nepse_client import __author__, __version__
except ImportError:
    __version__ = "1.0.0"
    __author__ = "Amrit Giri"

# -- Project information -----------------------------------------------------

project = "NEPSE Client"
copyright = f"{datetime.now().year}, {__author__}"
author = __author__
version = __version__
release = __version__

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here
extensions = [
    "sphinx.ext.autodoc",  # Auto-generate documentation from docstrings
    "sphinx.ext.napoleon",  # Support for NumPy and Google style docstrings
    "sphinx.ext.viewcode",  # Add links to highlighted source code
    # "sphinx.ext.intersphinx",  # Link to other project's documentation
    "sphinx.ext.todo",  # Support for todo items
    "sphinx.ext.coverage",  # Collect doc coverage stats
    "sphinx.ext.ifconfig",  # Include content based on configuration
    "sphinx.ext.githubpages",  # Create .nojekyll file for GitHub Pages
    "sphinx_rtd_theme",  # Read the Docs theme
    "sphinx_copybutton",  # Add copy button to code blocks
    "sphinx_autodoc_typehints",  # Better type hints support
    "sphinx.ext.autosummary",  # Add the autosummary extension
]

# Add any paths that contain templates here, relative to this directory
templates_path = ["_templates"]

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

# The suffix(es) of source filenames
source_suffix = {
    ".rst": "restructuredtext",
    ".md": "markdown",
}

# The master toctree document
master_doc = "index"

# The language for content autogenerated by Sphinx
language = "en"

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages
html_theme = "sphinx_rtd_theme"
html_baseurl = "https://nepse-client.readthedocs.io/"
# Theme options
html_theme_options = {
    "analytics_id": "",  # Google Analytics ID
    "logo_only": False,
    "prev_next_buttons_location": "bottom",
    "style_external_links": False,
    "vcs_pageview_mode": "",
    "style_nav_header_background": "#0078d7",
    # Toc options
    "collapse_navigation": False,
    "sticky_navigation": True,
    "navigation_depth": 4,
    "includehidden": True,
    "titles_only": False,
}

# Add any paths that contain custom static files (such as style sheets)
html_static_path = ["_static"]

# Custom sidebar templates
html_sidebars = {
    "**": [
        "globaltoc.html",
        "relations.html",
        "sourcelink.html",
        "searchbox.html",
    ]
}

# The name for this set of Sphinx documents
html_title = f"{project} v{version}"

# A shorter title for the navigation bar
html_short_title = "NEPSE Client"

# The name of an image file (relative to this directory) to place at the top
# of the sidebar
# html_logo = '_static/logo.png'

# The name of an image file (relative to this directory) to use as a favicon
# html_favicon = '_static/favicon.ico'

# If true, links to the reST sources are added to the pages
html_show_sourcelink = True

# If true, "Created using Sphinx" is shown in the HTML footer
html_show_sphinx = True

# If true, "(C) Copyright ..." is shown in the HTML footer
html_show_copyright = True

# Output file base name for HTML help builder
htmlhelp_basename = "nepseclientdoc"

# -- Options for autodoc -----------------------------------------------------

# This value selects what content will be inserted into the main body of an autoclass directive
autodoc_default_options = {
    "members": True,
    "member-order": "bysource",
    "special-members": "__init__",
    "undoc-members": True,
    "exclude-members": "__weakref__",
    "show-inheritance": True,
}

# This value controls how to represents typehints
autodoc_typehints = "description"

# This value controls the behavior of sphinx.ext.autodoc
autodoc_class_signature = "separated"

# -- Options for napoleon ----------------------------------------------------

# Napoleon settings for Google style docstrings
napoleon_google_docstring = True
napoleon_numpy_docstring = False
napoleon_include_init_with_doc = True
napoleon_include_private_with_doc = False
napoleon_include_special_with_doc = True
napoleon_use_admonition_for_examples = True
napoleon_use_admonition_for_notes = True
napoleon_use_admonition_for_references = False
napoleon_use_ivar = False
napoleon_use_param = True
napoleon_use_rtype = True
napoleon_use_keyword = True
napoleon_custom_sections = None

# -- Options for intersphinx -------------------------------------------------

# Example configuration for intersphinx: refer to the Python standard library
intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
    "httpx": ("https://www.python-httpx.org/", None),
}

# -- Options for todo extension ----------------------------------------------

# If true, `todo` and `todoList` produce output, else they produce nothing
todo_include_todos = True

# -- Options for coverage extension ------------------------------------------

coverage_show_missing_items = True

# -- Options for copybutton --------------------------------------------------

# Exclude copy button from appearing over line numbers
copybutton_exclude = ".linenos, .gp"

# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    "papersize": "letterpaper",
    "pointsize": "10pt",
    "preamble": "",
    "figure_align": "htbp",
}

# Grouping the document tree into LaTeX files
latex_documents = [
    (master_doc, "nepse-client.tex", "NEPSE Client Documentation", author, "manual"),
]

# -- Options for manual page output ------------------------------------------

# One entry per manual page
man_pages = [(master_doc, "nepse-client", "NEPSE Client Documentation", [author], 1)]

# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files
texinfo_documents = [
    (
        master_doc,
        "nepse-client",
        "NEPSE Client Documentation",
        author,
        "nepse-client",
        "Python client for Nepal Stock Exchange API.",
        "Miscellaneous",
    ),
]

# -- Options for Epub output -------------------------------------------------

epub_title = project
epub_exclude_files = ["search.html"]

# -- Custom configuration ----------------------------------------------------

# Syntax highlighting
pygments_style = "sphinx"

# Number figures
numfig = True

# Figure numbering
numfig_format = {
    "figure": "Figure %s",
    "table": "Table %s",
    "code-block": "Listing %s",
    "section": "Section %s",
}
